### PR TITLE
Disable OpenMP for AppleClang<13 by default

### PR DESCRIPTION
**Pull request by hsinfan1996**
Merge into PR #1017

### CODE REVIEW

**Comment by hsinfan1996** [comment]
https://github.com/conda-forge/pyccl-feedstock/pull/33

**Comment by beckermr** [comment]
I don't follow this pr at all. We've built openmp on apple for a long time now. The real problem is the cmake changes, right?

**Comment by beckermr** [comment]
Can't we just roll back the changes made originally for cmake?

**Comment by hsinfan1996** [comment]
Building ccl with AppleClang is mostly fine. However, there will be ImportError in python if libomp is found but not linked correctly. For OpenMP to work with AppleClang12, we need to link libomp with link_libraries in cmake (which breaks conda-forge build for arm64) or users need to set LDFLAGS manually. Now I am trying to revert the changes made for cmake while preventing the ImportError problem.

**Pull request closed without merging**
