### PR TITLE
Fix estimation of kernel support.

### PR DESCRIPTION
**Pull request by tilmantroester**
A more conservative estimate of the kernel support. Addresses #865.

### CODE REVIEW

**Review by damonge — APPROVED** [review]
LGTM!

**Comment by damonge** [comment]
@tilmantroester did you check that this fixes the KiDS-specific error you noticed?

**Comment by tilmantroester** [comment]
Yes, Cls look good now. The chi_min gets set to 0 now. Before it would get set to the first sampling point, which turned out to be z~0.05 ~ 200 Mpc:
lensing_tracer_chi_min

**Comment by damonge** [comment]
Great, let's merge! Thanks a lot @tilmantroester

**Pull request merged**
