### PR TITLE
Adds backup integration function for computing Cls

### PR DESCRIPTION
**Pull request by EiffL**
This pull request aims at addressing #302 where it was realized that the computation of Cls could fail unexpectedly when changing the IA amplitude. At the root of the problem was that for some `ell` the `gsl_integration_qag` function in `ccl_angular_cl` failed due to round-off errors before reaching the desired relative accuracy. To try to recover from such failures, I have added a backup integration strategy based on another gsl function which will try to compute the integral if the first method fails. This alternative method, based on  `gsl_integration_cquad` is in principle slower than the default method but should be more robust.

### CODE REVIEW

**Comment by EiffL** [comment]
One detail though, is there any mechanism in CCL to display warnings ? For instance to notify the user that the default integration failed?

**Comment by elisachisari** [comment]
I don't think we have a mechanism for warnings. Take a look at ccl_error.c in src/, there we have ccl_raise_exception. We could similarly have a ccl_raise_warning for this application.

**Comment by elisachisari** [comment]
I checked this out and used a jupyter notebook for computing Cl's for cosmic shear and gxy-gxy lensing including IA with amplitudes (bias_ia) ranging from 0 to 100 and for ells in the range [2,3000]. Everything worked well for me and checks pass in C and python. However, the same notebook worked fine for me in master as well, so I'd suggest for @joezuntz to check this PR solves his issue #302 specifically.

**Comment by EiffL** [comment]
I've  opened a  new  PR for this, starting from a clean version of master, we should close this PR and continue with the other one: #406

**Comment by EiffL** [comment]
This is now outdated and solved by another PR, closing this one.

**Pull request closed without merging**
