### PR TITLE
updated correlation.py to correlations.py to avoid import clash

### LINKED ISSUE #744: Update correlation documentation
The readthedocs documentation for correlation functions (including correlation_3d) is incorrect. It may be just that the function is incorrectly specified (with an extra `.correlation` in the call), but there may be other issues. We should also update documentation once the added functionality in Issue #743 is included.

### PR DESCRIPTION
**Pull request by jablazek**
This is pretty basic. Just trying to avoid a namespace clash. I don't think this will break the API, which was already broken by this clash.

Should resolve #744

### CODE REVIEW

**Comment by jablazek** [comment]
Although, it WILL break code that explicitly imports the desired function with `import pyccl.correlation.correlation_3d` or similar.

I have updated the name of the file in tests/ to reflect the new correlations.py name. Within that test, it was already using the full import `pyccl as ccl` option. The benchmarks appear to test the actual `correlation` function in its own file, so no name change is needed there.

**Review by beckermr — APPROVED** [review]

**Comment by jablazek** [comment]
How does coveralls work? It seems not to recognize that correlation.py has been replaced. Is this because the build is failing?

**Comment by beckermr** [comment]
Fix the build and then worry about it.

**Comment by jablazek** [comment]
OK, I think that builds will all fail until the change to github actions. So we can wait.

**Comment by jablazek** [comment]
@beckermr, I think we're good now with the build and coveralls.
@c-d-leonard, any comments before we merge?

**Comment by damonge** [comment]
Just checking: are we waiting on anything here @jablazek @c-d-leonard ?

**Comment by beckermr** [comment]
Let's merge.

**Pull request merged**
