### PR TITLE
ENH tag v2

### PR DESCRIPTION
**Pull request by beckermr**
This Pr has a few minor changes to tag v2.

### CODE REVIEW

**Comment by elisachisari** [comment]
In the developer's installation in readthedocs.org, we need to clarify that CAMB needs to be installed first. It won't prevent the library from installing, but it will prevent unit tests from running.

**Comment by elisachisari** [comment]
Can we also specify how to *uninstall* the library both for developers and users?

**Comment by beckermr** [comment]
Alright @elisachisari! I have made all of the updates/additions you asked for!

**Comment by elisachisari** [comment]
Still going through the code and instructions. Could we possibly clarify all defaults here:
https://ccl.readthedocs.io/en/latest/source/notation_and_other_cosmological_conventions.html#models
E.g. for keywords like "matter_power_spectrum".

**Comment by beckermr** [comment]
ohhhh

**Comment by beckermr** [comment]
done.

**Pull request merged**
