### PR TITLE
Implement Gaussian photo-z convenience function.

### LINKED ISSUE #210: Consider making a default Gaussian photo-z function
This would be able to be called by the user instead of a user defined photo-z function.

### PR DESCRIPTION
**Pull request by philbull**
Fixes #210.

### CODE REVIEW

**Comment by philbull** [comment]
@elisachisari @c-d-leonard I've now fixed all the conflicts with master. Hopefully ready to merge now.

**Comment by elisachisari** [comment]
hi @philbull @c-d-leonard. I think there was a bug in the normalization of the gaussian_pz function. I realized by comparing ccl_sample_run.c with ccl_lsst_specs.c. Please check whether you agree with my latest commit.

**Comment by elisachisari** [comment]
@philbull @c-d-leonard Can you follow up on the bug mentioned above?

**Comment by c-d-leonard** [comment]
Hi @elisachisari. Sorry! I totally missed your message on July 14. I will try to look at this today or tomorrow.

**Comment by c-d-leonard** [comment]
@elisachisari I have checked your modifications and I agree with them. Happy to approve if others are happy.

**Comment by elisachisari** [comment]
thanks @c-d-leonard. I would suggest adding an example in the Photo-z jupyter notebook before merging. @philbull: do you agree with my changes and do you think you could add a minimal example in the notebook?

**Comment by c-d-leonard** [comment]
Hi @elisachisari I just had a look to see about adding an example to the Photo z ipython notebook but it looks like @philbull had previously added something. Was there something more you were thinking of than what he has put there already?

**Comment by philbull** [comment]
@elisachisari I agree with your changes - good catch! I also fixed a related bug in the example in the Jupyter notebook, where the same normalisation error was being made.

There is already an example that uses the new built-in Gaussian photo-z function in the Jupyter notebook.

I also merged `master` into this, so in principle this is ready to merge if you approve.

**Comment by philbull** [comment]
I fixed a small merge conflict, tested, and then merged into `master`.

**Pull request merged**
