### PR TITLE
Move example code/scripts to a separate directory

### PR DESCRIPTION
**Pull request by philbull**
Moves example code to its own directory, away from the tests, and updates the README and Makefile as appropriate.

Also removes some old entries in the Makefile, and some legacy examples that were still hanging around.

### CODE REVIEW

**Comment by philbull** [comment]
(This replaces some parts of PR #211, which is outdated.)

**Comment by elisachisari** [comment]
Looks good. Thanks for sandbox additions too. Could you edit the README and CCL note to match your changes?

**Comment by philbull** [comment]
The README should be updated, but I forgot about the note. I'll fix that.

**Comment by philbull** [comment]
OK, done.

**Comment by philbull** [comment]
I checked, and I don't see any mention of the sandbox files anywhere else. They were very old, and didn't look like functioning code anyway. So I think we're good to drop them. I'll merge into `master` now. Thanks!

**Pull request merged**
