### PR TITLE
Tidy up and improve tests

### PR DESCRIPTION
**Pull request by philbull**
This pull request makes some minor changes to the way tests are performed.
- Moves example code out of the `tests/` directory and into a new `examples/` directory
- Generalises some tests to use CLASS P(k) as well as BBKS P(k)
- Adds validation code for CLASS P(k) accuracy, using high-precision CLASS run as a reference

### CODE REVIEW

**Comment by elisachisari** [comment]
@philbull I think these are good tests to include. This branch compares CLASS direct outputs of the linear power spectrum to the CCL output. It also cleans up names and comments. I think the other branch @villarrealas and I were working on was mainly for the purpose of checking spline stability and won't necessarily be merged onto master, although I expect we will need to revisit it. If @mishakb can give you his review for this branch, I think it would be good to merge it.

**Comment by mishakb** [comment]
@philbull @elisachisari  @damonge, @villarrealas  the make check runs fine when I tested it but looking at the files in CCL/tests/benchmark/class_benchmark, there seem to be some redundancies between the ini files and between some corresponding output files. Namely, Files with ...mod1... mod2 ... mod3 ...  have the same content.  Do these need some cleaning or a readme file to explain why there are 3 instances?  Also, at the end of file cc_test_class.c, maybe a few line are needed to explain why those commented out failed CTEST2 are kept there and what needs to be done about them in the future.

**Comment by mishakb** [comment]
@philbull let me know about previous comments so maybe we can close this PR. Thanks.

**Comment by philbull** [comment]
I think this PR should be closed, as #331 does a better job of moving the examples, and more thought needs to go into the CLASS tests.

**Pull request closed without merging**
