### PR TITLE
Update physical constants CODATA 2022

### PR DESCRIPTION
**Pull request by pennalima**
Update physical constants and derived ones according to CODATA 2022 and IAU 2015:

Newton's gravitational constant (G)
Solar mass (compatible with G)
Rho critical (compatible with G and solar mass)
Boltzmann constant
Stefan-Boltzmann constant
Planck's constant
Electron volt

Pages: CODATA 2022 https://physics.nist.gov/cuu/Constants/index.html (for example, see All values (ascii))
IAU 2015 resolutions: https://www.iau.org/static/resolutions/IAU2015_English.pdf

### CODE REVIEW

**Comment by pennalima** [comment]
Hi @damonge and @nikosarcevic, 

I updated some physical constants according to CODATA 2022. But some benchmarks are failing now. 
We need to generate the following files again: pt_bm_lpt_z0.txt and pt_bm_lpt_z1.txt. They are called in benchmarks/test_ptpk_lpt.py.    
Do you know who (or how) to generate these files?

**Comment by nikosarcevic** [comment]
> Hi @damonge and @nikosarcevic,
> 
> I updated some physical constants according to CODATA 2022. But some benchmarks are failing now. We need to generate the following files again: pt_bm_lpt_z0.txt and pt_bm_lpt_z1.txt. They are called in benchmarks/test_ptpk_lpt.py. Do you know who (or how) to generate these files?

Hi, Marianna,

I was busy last week with the viva and I want to finish something before Thursday. Maybe if you can show up in the forecasting telecon this week and we can go over it?

Also, @damonge  -- when will we have the ccl telecon? would be good to start it now that September is here.

**Comment by pennalima** [comment]
Hi @nikosarcevic , 

Talk to you on Thursday.

**Comment by damonge** [comment]
I think this is due to an update in velocileptors, and has nothing to do with the constants update. I've updated the benchmarks. Let's see if that does it.

**Comment by damonge** [comment]
@pennalima this seems to have worked. Is this ready for a review?

**Comment by pennalima** [comment]
Hi @damonge, 

Thanks a lot for checking it. 
Yes, it is ready for review.

**Review by damonge — APPROVED** [review]
LGTM!

**Comment by damonge** [comment]
Great, done! Feel free to merge.

**Pull request merged**
