### PR TITLE
Updating benchmark comparison notebook to v2

### PR DESCRIPTION
**Pull request by elisachisari**
Related to issue #695.

### CODE REVIEW

**Comment by elisachisari** [comment]
Some progress on this: I was able to bring most of the tests to their original status by matching the tests/test*py set-ups. There are still some issues: power spectra have decreased in accuracy for some splines and for cases with massive neutrinos. Some of this could be linked to my set-up (4 tests failing in this computer, though travis says everything is ok). But not all the failures are due to this. The spline accuracy check has decreased in quality since v2, not only for this computer.

**Comment by elisachisari** [comment]
Problems currently encountered in insets 21,22,26.

**Comment by elisachisari** [comment]
Also 25 (baryons) has decreased in accuracy

**Comment by elisachisari** [comment]
The most recent commit runs the benchmark notebook using a system where the tests (except new fast-pt capability) are passing. 

The changes in the benchmark notebook I was able to identify compared to the previous released version are:
* The BCM test decreased from 1e-12 to 1e-9. However, the tolerance in the python test is set to 1e-4, so it is obviously still passing.
* The spline accuracy checks look very different. I can’t find this anywhere in the repo. I think this test was removed if it was ever run automatically in the test suite.
* C_ell plots have changed in detail, but maintain the same accuracy. It could be a consequence of changes in some integration parameters, or minor differences in the cosmology that I haven’t been able to match.
* xi_3D also changed a bit, but the order of magnitude of the accuracy checks has remained the same.
* All non Limber plots have been removed.

**Comment by c-d-leonard** [comment]
@elisachisari looks like you've added the last plot - any idea what's happening with the one travis test failing? I've not seen that issue before. I'll approve as soon as we resolve that.

**Comment by elisachisari** [comment]
This looks like a travis internal problem. I re-started the jobs there.

**Comment by elisachisari** [comment]
@c-d-leonard Tests pass now, I brought master in and that solved the issue.

**Comment by c-d-leonard** [comment]
Sorry for the delay on this. Looks great! I'm approving - want to do the honours of merging @elisachisari?

**Pull request merged**
