### PR TITLE
Tinker10 normalization

### PR DESCRIPTION
**Pull request by damonge**
The Tinker 2010 mass function should be normalized such that Eq. 7 of https://arxiv.org/pdf/1001.3162.pdf holds at all redshifts. However, currently this is only satisfied at redshift z=0, which has been a common mistake in several implementations of this parametrization.

This PR implements an extended parametrization that fixes this issue, allowing users to select the "z=0 only" or "all z" normalization.

### CODE REVIEW

**Comment by damonge** [comment]
I should thank @borisbolliet, @msyriac and others for figuring this out

**Comment by c-d-leonard** [comment]
Thanks @damonge, is this ready to look at?

**Comment by damonge** [comment]
Yep!

**Comment by c-d-leonard** [comment]
@pennalima @villarrealas any chance either / both of you want to take a look at this?

**Comment by c-d-leonard** [comment]
@damonge did you end up pinging Matt M. for review on this as you mentioned?

**Comment by damonge** [comment]
I just did. @msyriac do you mind checking this one out?

**Comment by pennalima** [comment]
Sorry @c-d-leonard , I missed the message. 
I can review it.

**Review by pennalima — APPROVED** [review]

**Comment by damonge** [comment]
thanks @pennalima !

**Pull request merged**
