### PR TITLE
1-halo trispectrum

### PR DESCRIPTION
**Pull request by damonge**
This first PR implements the 1-halo trispectrum integral

### CODE REVIEW

**Comment by damonge** [comment]
alright, @anicola, last one for now

**Review by anicola — COMMENTED** [review]
This looks great to me @damonge. The only comment I have is that 
T_{u_1,u_2;v_1,v_2}(k_u,k_v,a) = I^0_{2,2}(k_u,k_v,a|u_{1,2},v_{1,2}) 
is an approximation that is not generically true. I think this should be clarified somewhere.

**Comment by damonge** [comment]
Ah, good point @anicola . Just added a note in the docs.

**Review by anicola — APPROVED** [review]
Great! Thanks a lot for the changes @damonge!

**Pull request merged**
