### PR TITLE
Add support for python 3.x

### LINKED ISSUE #133: Support to python 3.x?
I was trying to install the libraries using anaconda python 3.5 and I had some trouble related to SWIG.

Is python 3.x supported (or are we planning to support it) or right now are we only supporting python 2.7?

Has someone installed the library using python 3.x?

### PR DESCRIPTION
**Pull request by dkirkby**
I tested this against anaconda + py3.6, but someone should check that I didn't break anything for py2.7.

Fortunately, the existing swig'd `ccl_wrap.c`, etc, worked without any changes, so we do not need to maintain separate swig outputs for py2 and py3 :smile:

I checked that `python run_tests.py` still works and I can run all of the notebooks under `tests/` (but I had to fix some print statements and change the metadata associated with the kernel, so I didn't save the changes).

Fixes #133

### CODE REVIEW

**Comment by dkirkby** [comment]
Travis tests are failing, but I'm guessing this is unrelated to this PR?

**Comment by elisachisari** [comment]
Yes, travis tests are not yet working. They are enabled right now because of debugging in that branch.

**Comment by dkirkby** [comment]
@damonge Can you post the results of your py2.7 test here?  How did you install pyccl (pip / setup.py, system / user ?)

**Comment by damonge** [comment]
Currently getting:
```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyccl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damonge/.local/lib/python2.7/site-packages/pyccl/__init__.py", line 4, in <module>
    from pyccl import core, constants, background, power, massfunction
  File "/home/damonge/.local/lib/python2.7/site-packages/pyccl/core.py", line 5, in <module>
    from pyccl.pyutils import check 
  File "/home/damonge/.local/lib/python2.7/site-packages/pyccl/pyutils.py", line 4, in <module>
    from pyccl import core
ImportError: cannot import name core
>>> 
```
CCL was installed as `python setup.py install --user`

**Comment by dkirkby** [comment]
@damonge It looks like you uncovered a circular import (core -> pyutils -> core). Can you try again with my last commit to try and work around this?

**Comment by damonge** [comment]
Seems to work now! I've managed to run the python tests successfully

**Comment by dkirkby** [comment]
@philbull Do you want to review this before we merge?

**Comment by hsnee** [comment]
passed all tests on homebrew's python 3.6

**Comment by dkirkby** [comment]
Thanks @hsnee!  Several people also commented in slack that this worked for them, so I think we are ready to merge.

**Comment by elisachisari** [comment]
It looks like this PR only needs an official review for merging.

**Comment by philbull** [comment]
Sorry for the delay. I can confirm that this patch works very well, and the wrapper seems to work well in both Python 2.x and 3.x.

I merged the latest `master` into this branch, which led to some merge conflicts due to the new `setup.py` script. I merged those changes in and re-tested in both Python 2.7 and 3.5, and everything seems to be working well.

**Pull request merged**
