### PR TITLE
Fix photo-z notebook crash

### LINKED ISSUE #503: bug in photo-z functions from python
The photo-z functions don't appear to run right now. See the example notebook.

### PR DESCRIPTION
**Pull request by philbull**
This fixes the crash in the photo-z example notebook. It was caused by the `ccl_gsl` struct not being initialised in a particular edge case (when no `ccl_parameters` object has previously been created). I added guards that prevent uninitialised `ccl_gsl` from sneaking through.

Closes #503

### CODE REVIEW

**Comment by elisachisari** [comment]
Travis is failing here again - it seems to be the samek flake8 issue we were encountering yesterday.

**Comment by beckermr** [comment]
I fixed that issue in another PR. We can ignore the failure and merge.

**Comment by elisachisari** [comment]
@beckermr which PR fixed the flake8 issue?

**Comment by philbull** [comment]
OK, merging. I agree that the test failure isn't an important one.

**Comment by beckermr** [comment]
@elisachisari The code review 2 PR I just merged.

**Pull request merged**
