### PR TITLE
Adding implementation of power spectrum needed for effective halo model of Philcox et al., 2020

### PR DESCRIPTION
**Pull request by anicola**
This PR adds a power spectrum calculator that computes the IR resummed one-loop power spectrum with counterterms as needed in the implementation of the effective halo model of Philcox et al., 2020.
This still lacks unit tests and benchmarks but I will add these later.

### CODE REVIEW

**Comment by c-d-leonard** [comment]
@anicola what is the status of this?

**Comment by anicola** [comment]
Hi @c-d-leonard! 
Sorry for being so slow on this! I still need to make the code flake8 compatible and write unit tests. I plan to do this during sprint week, if that's ok?

**Comment by c-d-leonard** [comment]
No worries! I'll be sprinting that week so will be around if you need any help with that. Consider adding a sprint to the list [here](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2020+Virtual+Sprint+Week%3A+Sprints) and tagging with 'ccl'?

**Comment by c-d-leonard** [comment]
@anicola any updates on this? Let me know if you need any help with flake8 or unit tests!

**Comment by c-d-leonard** [comment]
@damonge @anicola This PR has been hanging around for quite some time. It is still something we want to merge in some form? Do we need to find someone new willing to push it over the line?

**Comment by damonge** [comment]
After chatting with @anicola , we decided to archive this for now. We can reopen if this is needed in the future.

**Pull request closed without merging**
