### PR TITLE
Give useful error message when trying to pass decreasing a array to CalculatorCosmology

### PR DESCRIPTION
**Pull request by tilmantroester**
Addresses issue #863.

### CODE REVIEW

**Comment by tilmantroester** [comment]
I ran into another unhelpful error message when the tracer and power spectra have different a_max. I'll add a check for that as well.

**Comment by damonge** [comment]
@tilmantroester did you want to add more changes? Otherwise this looks good to me.

**Comment by tilmantroester** [comment]
@damonge I've now added a check in Pk2D as well.

I found that if the redshift ranges of the tracers and P(k) don't agree then this sometimes causes integration errors. Should that be left to the user to figure out or should this cause a warning?

**Comment by damonge** [comment]
Humm, I think it should be up to the users to provide Pk arrays that cover the appropriate range of k/a for their purposes. But is the error message particularly obscure in this case?

**Comment by tilmantroester** [comment]
It's a C-level integration error in `angular_cl` and should only occur when using custom P(k) arrays. I guess at that point users can be expected to check that their inputs are consistent.

**Comment by damonge** [comment]
Maybe we could add a check at the C-level comparing the limits in k and a of the tracers and power spectra. I'm happy for that to be addressed somewhere else.

**Review by damonge — APPROVED** [review]
LGTM!

**Comment by tilmantroester** [comment]
Thanks for the review!
I have a python-level check that I can polish if that issue comes up again.

**Pull request merged**
