### PR TITLE
add kwargs option to Cosmology.read_yaml and tests

### PR DESCRIPTION
**Pull request by joezuntz**
We have need of this change to read_yaml in TXPipe to let us override things we load.

Someone who knows more about CCL's changes over the last year or two should probably also check that nothing is missing from Cosmology.read_yaml.

### CODE REVIEW

**Comment by tilmantroester** [comment]
Looks good to me. I guess master needs to be merged in to switch to GHA.

**Comment by c-d-leonard** [comment]
@joezuntz I'll go ahead and merge master in and then we can merge this?

**Comment by joezuntz** [comment]
I've re-merged master since there seemed to be some more changes, then happy for you to click the merge button if the tests pass.  Thanks!

**Review by damonge — APPROVED** [review]
LGTM!

**Pull request merged**
