### PR TITLE
Angular power spectrum covariance Limber integrator

### PR DESCRIPTION
**Pull request by damonge**
Transform a 3D connected trispectrum into the corresponding angular power spectrum covariance.

### CODE REVIEW

**Comment by damonge** [comment]
@anicola this one is also ready for review, but you should only look at it after #835

**Comment by anicola** [comment]
Looks great to me @damonge!

**Comment by anicola** [comment]
Looks great to me @damonge!

**Review by anicola — APPROVED** [review]
This looks great to me @damonge!

**Pull request merged**
