### PR TITLE
Bbks fix v1

### PR DESCRIPTION
**Pull request by damonge**

### CODE REVIEW

**Comment by beckermr** [comment]
We need to add an entry to the change log.

**Comment by damonge** [comment]
Would that be within the `v 1.0 API changes` section?

**Comment by beckermr** [comment]
I think it should go in a new section. We'll have to make sure the one on master matches but we can do that later.

**Comment by damonge** [comment]
Didn't you fix a bunch of things in v1 recently? I couldn't see those changes

**Comment by beckermr** [comment]
Hmmmm. The commits are there. https://github.com/LSSTDESC/CCL/commits/releases/1.0

You may need to update your local branch.

**Comment by damonge** [comment]
Damn, I branched off from a wrong point. Ignore this, I'll make a new PR

**Pull request closed without merging**
