### PR TITLE
Add a simple Python script to run timing benchmarks

### PR DESCRIPTION
**Pull request by philbull**
This PR implements a simple script to run a few timing benchmarks. Only a single distance function and several matter power spectrum functions are timed at the moment. The results on my machine (4yo Dell XPS 13, Intel i7) are:

```
Timing luminosity distance...
	Runtime: 0.124 +/- 0.003 sec
Timing matter power (Eisenstein + Hu)...
	Runtime: 0.066 +/- 0.003 sec
Timing matter power (Boltzmann)...
	Runtime: 5.195 +/- 0.029 sec
Timing matter power (Boltzmann + Halofit)...
	Runtime: 5.193 +/- 0.271 sec
Timing matter power (cosmicemu)...
	Runtime: 4.916 +/- 0.689 sec
```

### CODE REVIEW

**Comment by damonge** [comment]
@philbull : might be worth coordinating with @elisachisari , since we've been doing something similar for a typical likelihood evaluation

**Comment by philbull** [comment]
It's curious that all of the power spectrum methods take roughly the same time, by the way... I'll have a go at profiling them to see what the bottleneck is.

**Comment by elisachisari** [comment]
I added another timing benchmark from @damonge and myself. Probably someone else should review.
These are the timings I'm obtaining for the two scripts running on my desktop:

For ccl_timing_benchmark.py:
Timing luminosity distance...
       Runtime: 0.110 +/- 0.001 sec
Timing matter power (Eisenstein + Hu)...
       Runtime: 0.048 +/- 0.001 sec
Timing matter power (Boltzmann)...
       Runtime: 4.153 +/- 0.124 sec
Timing matter power (Boltzmann + Halofit)...
       Runtime: 4.126 +/- 0.117 sec
Timing matter power (cosmicemu)...
       Runtime: 3.918 +/- 0.141 sec

For the three likelihood evaluations:
Run 1
Run parameters:
 Vanilla LCDM
 10 tomographic bins
 RSD  : yes
 IAs  : yes
 Magnification : yes

Cosmology creation: 0.00019 s
P(k) call: 2.34753 s
Tracer creation: 0.30173 s
210 Cls: 15.10384 s
265 correlation functions: 0.50385 s
Total time ellapsed: 18.25715 s

Run 2
Run parameters:
 LCDM + m_nu
 10 tomographic bins
 RSD  : no
 IAs  : yes
 Magnification : yes

Cosmology creation: 0.02122 s
P(k) call: 27.95052 s
Tracer creation: 0.44888 s
210 Cls: 9.77813 s
265 correlation functions: 0.50089 s
Total time ellapsed: 38.69964 s

Run 3
Run parameters:
 CosmicEmu
 10 tomographic bins
 RSD  : yes
 IAs  : yes
 Magnification : yes

Cosmology creation: 0.00020 s
P(k) call: 4.03509 s
Tracer creation: 0.30479 s
210 Cls: 15.28589 s
265 correlation functions: 0.50194 s
Total time ellapsed: 20.12791 s

**Comment by beckermr** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
