### PR TITLE
Fix unit tests on macOS

### PR DESCRIPTION
**Pull request by hsinfan1996**
Fix a warning on ambiguous package distribution. (Installing with develop mode "-e" will not see the warning.)

### CODE REVIEW

**Comment by hsinfan1996** [comment]
Somehow this PR also fixes unit tests on macOS.

**Comment by hsinfan1996** [comment]
To suppress other warnings, we should turn to PR #1144, which I think is ready to be merged.

**Comment by damonge** [comment]
@hsinfan1996 thanks for this. #1144 is merged, and I can review this as soon as conflicts are resolved.

**Comment by hsinfan1996** [comment]
I was going to make this PR a fix to setup.py before we merge PR #1144. But it is still good to just fix the unit tests on macOS.

**Comment by hsinfan1996** [comment]
@damonge Thank you. This PR is ready for review. For the changes in `pyproject.toml`, I only move the item up to make it more clear.
Interestingly, CI on macOS now runs faster than on Ubuntu. (It was way slower.)

**Review by damonge — APPROVED** [review]
LGTM! Thanks a lot @hsinfan1996

**Pull request merged**
