### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by jkuruvilla**
This PR deals with setting up Azure Pipelines as the CI engine. Helps out with #477 

Pros: 
- Allows for parallel testing (upto 10 builds)
- Allows for better log monitoring 

Sample log for the build can be seen [here](https://dev.azure.com/jkuruvilla-ci/jkuruvilla-ci/_build/results?buildId=93&view=logs)

### CODE REVIEW

**Comment by elisachisari** [comment]
hi @jkuruvilla! Thanks for opening this PR. It would be great if you could join the CCL Slack channel #desc-ccl to introduce yourself and to interact with the team. Importantly, that's where we make all the telecon announcements.

**Comment by jkuruvilla** [comment]
@elisachisari I would be happy to do that. However since I am not a member of the LSSTDESC, I don't have access to the slack server. Let me know if you could invite me (if possible). You can see a brief introduction about myself [here](https://jkuruvilla.github.io/)

**Comment by beckermr** [comment]
Thank you for the contribution! I really like azure CI (which is weird to me since microsoft but hey w/e).

One question. Travis runs the builds in parallel too. I am confused about the timing numbers you put above.

**Comment by jkuruvilla** [comment]
> I really like azure CI (which is weird to me since microsoft but hey w/e).

Same for me! 

> One question. Travis runs the builds in parallel too. I am confused about the timing numbers you put above.

@beckermr  I think I may have messed up the timings. I will edit it out and can change the title too. But does travis build push and the pr build simultaneously?

**Comment by beckermr** [comment]
I think for travis it depends on how much capacity they have? I don't know. 

I will say though that most of the CI time is compiling code and then some v slow tests.

We should probs switch to azure either way.

**Comment by jkuruvilla** [comment]
> I will say though that most of the CI time is compiling code and then some v slow tests.
 
For example, here I installed swig through conda and seemed to have shaved off some time while building. I can try the same for gsl and fftw3, and see how it goes. Also do you know why macOS seems to take ~17 minutes for the nosetests while linux takes ~10 minutes?

**Comment by beckermr** [comment]
IDK why the mac ones are slow, but my guess are two things:

1. The actual mac hardware might be older.
2. The build for osx doesn't use openmp right now.

Pulling some of the deps from conda is what I do locally. Def a good idea!

**Comment by beckermr** [comment]
Hmmmm. Travis appears to be running all of the builds at once right now. I think given that, we might as well punt on azure for a bit. Is it ok if I close this and then we can revisit in the future?

A PR pulling more deps from conda would be good for the travis build.

**Comment by jkuruvilla** [comment]
Okay sure thing, I can close it :+1:

**Pull request closed without merging**
