### PR TITLE
Moved Cell tests C->python

### PR DESCRIPTION
**Pull request by damonge**
I've moved the C_ell tests from C to python. This will be necessary once the work in #627 is done, since none of the stuff currently tested in C will live in C. Thoughts @elisachisari @beckermr ? If you agree with this I'll move the correlation function tests too, since those will become obsolete as well.

### CODE REVIEW

**Comment by damonge** [comment]
> We need to be making proper use of parametrized tests here. See the pytest documentation.

Sorry @beckermr , I don't know what this means. I had a quick look at [this](https://docs.pytest.org/en/latest/parametrize.html) but I don't know exactly what you're looking for.

**Comment by beckermr** [comment]
So what I mean here is that there is a lot of repeated code testing all of the different cases. The parametrized tests allow pytest to separate out each test and have the added benefit that if one fails it will still run the rest of them.

**Comment by damonge** [comment]
@beckermr alright, how about now?

**Comment by beckermr** [comment]
Looks great! One more thing. We should preserve the link between the benchmarks themselves and the code that generated them. Right now the files were moved, but we won't be able to easily track this all down later. 

IDK how exactly to do this. Maybe @elisachisari has some thoughts here?

**Comment by damonge** [comment]
We could keep the files in both the `benchmarks/data` and the `tests/benchmarks` directories until  all tests have been migrated, but the size of the repo will increase

**Comment by beckermr** [comment]
Hmmmm. Can we move the scripts over? We can tell flake8 to ignore them using the exclude argument. It might be good organize the files with the benchmark data into directories instead of a grab bag of stuff all in one spot.

**Comment by damonge** [comment]
The codes that generated the benchmarks live here:
https://github.com/LSSTDESC/CCL/tree/master/tests/benchmark/codes

They're all there with a README that explains what to do in order to reproduce things. So we could move that whole directory over into `benchmarks`, but then the tests that currently reside in `tests` will be disconnected from them. We could also move things gradually, but maintaining two separate READMEs while this happens is going to be a pain and probably lead to inconsistencies in the end result...

**Comment by beckermr** [comment]
Ahhhh OK. Let's make an issue to move it and leave it in place for now then.

**Comment by damonge** [comment]
OK, great. Do you mean move the benchmark files back to where they were before?

**Comment by beckermr** [comment]
We can move the files, but we should make an issue to move the code.

**Comment by damonge** [comment]
OK, good. I'll make an issue then. Should I add this to the CHANGELOG? Not sure this qualifies as code change.

Anything else?

**Comment by beckermr** [comment]
We can punt on the changelog and make one entry later.

**Pull request merged**
