### PR TITLE
ENH updated the examples and benchmarks

### PR DESCRIPTION
**Pull request by beckermr**
This PR updates the examples and benchmarks.

### CODE REVIEW

**Comment by beckermr** [comment]
@rmjarvis My plan was to update all of the examples in this PR. I know this will leave the repo in a middle state for a bit, but I thought it would make code review easier. That seem good to you?

**Comment by beckermr** [comment]
OK @tmcclintock and @elisachisari - I have updated all of the examples and other scripts in the repo. I did not rerun the scripts in the benchmarks directory out of fear. I also found a bug which I am making an issue for here. I won't get to it before the end of the day. Might be a good hackweek thing.

https://github.com/LSSTDESC/CCL/issues/503

**Comment by beckermr** [comment]
I may be out of contact as you all look through this. All of the notebooks except the buggy one run fine so we are good to merge this really. I also updated some of the text where it made sense and I caught it.

**Comment by beckermr** [comment]
@tmcclintock @elisachisari bump on this - better to merge this sooner rather than later

**Comment by philbull** [comment]
I am working on a review now.

**Comment by beckermr** [comment]
OK @philbull . We don't need to go through this with a fine tooth comb. I changed calls to CCL but left the examples intact otherwise. We really should just merge this and get on with it. Your time is probably better spent doing something else.

**Comment by tmcclintock** [comment]
I have also started my review.

**Comment by philbull** [comment]
I made use of the opportunity to go through and tidy up several of the notebooks (typos, bad formatting etc). Sorry to complicate things by adding them to this PR, but I think the changes should be pretty uncontroversial, and it'll be good to get @tmcclintock's feedback while he's working through this anyway.

**Comment by beckermr** [comment]
Sounds good. When @tmcclintock is ready, he can merge the code.

**Comment by philbull** [comment]
This PR is currently failing the CI tests, but due to `flake8` rather than the test suite. When did this get switched on? It looks like it might be being a bit aggressive with the "unused variables" setting, although it has found some actual invalid characters in some of the files too.

**Pull request merged**
