### PR TITLE
added halo profiles to ccl note

### PR DESCRIPTION
**Pull request by KuanWang-Astro**
Description of halo profiles in CCL note

### CODE REVIEW

**Comment by elisachisari** [comment]
Compiles locally for me. I think the only thing missing is the 2D NFW description. It seems we also have that capability from the docs:
https://ccl.readthedocs.io/en/v2.0.0/api/pyccl.haloprofile.html
@damonge are there any updates needed based on the new halo modelling capabilities?

**Comment by damonge** [comment]
OK, I'm gonna add information about the latest version of the halo profiles that just got merged into master and we'll take it from there.

**Comment by damonge** [comment]
OK, I've added to @KuanWang-Astro 's text and described the new halo profile functionality. @elisachisari if you're OK with it I'm happy to merge this.

**Comment by damonge** [comment]
Humm, the docs don't seem to be up to date. Let me have a look at rtd.

**Comment by damonge** [comment]
OK, here we go @elisachisari . The new profiles are documented here: https://ccl.readthedocs.io/en/master/api/pyccl.halos.profiles.html

**Comment by damonge** [comment]
I could add a line on the old profile docs clarifying that these are deprecated (people can use them, but we'll remove them eventually)

**Comment by elisachisari** [comment]
Yes, I think this is a good idea

**Comment by damonge** [comment]
OK, done! (should appear in RTD after merging)

**Pull request merged**
