### PR TITLE
ENH add a custom CCLError

### LINKED ISSUE #473: make a `CCLRuntimeError` class
@rmjarvis suggested we swap out the `RuntimeError` in the `core.check` function for a custom error class.

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds a custom CCL error.

Closes #473

### CODE REVIEW

**Comment by beckermr** [comment]
This one is good to go!

**Comment by beckermr** [comment]
Indeed. atom has a nice global search. Aint none left!

**Comment by rmjarvis** [comment]
Oh, one comment though.  The coverage decrease is probably due to the new code.  Should probably add some simple unit tests that a `CCLError` reprs properly, and that two different ones are unequal and have different hashes.

**Comment by beckermr** [comment]
Ack will do. I copied the methods out of galsim so this should be fine. Sit tight.

**Pull request merged**
