### PR TITLE
Parallel lensing kernel

### LINKED ISSUE #719: PERF add OpenMP to the lensing tracer window function integrals
This is the next thing taking time.

### PR DESCRIPTION
**Pull request by damonge**
Closes #719

### CODE REVIEW

**Comment by damonge** [comment]
Great! Can you have a look at #727 when you get a chance (since you're in an OpenMP streak ;-)?

**Comment by beckermr** [comment]
Ack I missed that one. If you "assign" me on the PRs, I will get a notification and can find them more easily.

**Comment by damonge** [comment]
I know, but lately it seems like I'm asking you to review everything, so I was waiting to see if someone else would pick it up...

**Comment by beckermr** [comment]
No worries. I am always here to do review!

**Comment by damonge** [comment]
You're a hero

**Pull request merged**
