### PR TITLE
Neutrinos, parameters, power in v3

### PR DESCRIPTION
**Pull request by damonge**
Well, that

### CODE REVIEW

**Review by nikfilippas — CHANGES_REQUESTED** [review]
The main comment has to do with `T_ncdm`. It is a good idea to move it before we ship v3 so we don't have any more breakages in the future.

**Comment by nikfilippas** [comment]
@damonge I created #1049 to save you time, moves `T_ncdm` to `Cosmology` and removes `T_CMB` from `nu_masses`. It has this PR as its base, so have a look at the diffs and if you agree let's merge it here.

**Comment by damonge** [comment]
I think this is back to you @nikfilippas

**Review by nikfilippas — APPROVED** [review]
I flaked it - this ended up being trickier than we originally thought, but it looks good now!

**Pull request merged**
