### PR TITLE
Projected correlation function support

### PR DESCRIPTION
**Pull request by chrgeorgiou**
This PR adds support for computing projected correlation functions with CCL. These have the form:

$w_{ab}(r_p)=\int dz \ W(z)\int\frac{dk \ k}{2\pi^2} \ P(k,a) \ J_n(k \ r_p)$

with $W(z)$ a window function that depends on the redshift distribution, $P(k,a)$ the relevant power spectrum and $J_n$ the bessel function. This function is often used in direct measurements of galaxy clustering and intrinsic alignments. 

This PR uses the FFTLog wrapper in CCL (similarly to what is used in the halo model) to speed-up the integration.

### CODE REVIEW

**Comment by damonge** [comment]
@chrgeorgiou can I check what the status of this PR is?

**Comment by chrgeorgiou** [comment]
Hi @damonge, I just received a benchmark code from Elisa, I will tick the points raised above soon and update the PR.

**Comment by damonge** [comment]
@chrgeorgiou @elisachisari can I check what the status of this is? Is it meant to be ready for review?

**Comment by chrgeorgiou** [comment]
Hi David, I think the development is enough to have this merged from my side, but I would like to hear what Elisa thinks as well.

**Comment by nikosarcevic** [comment]
> Hi David, I think the development is enough to have this merged from my side, but I would like to hear what Elisa thinks as well.

what is the status of this? woudl be great if this was in ccl now.

**Pull request closed without merging**
