### PR TITLE
Fix cpp compatibility

### PR DESCRIPTION
**Pull request by vrastil**
added `__cplusplus` guards -- tested with CCL compiled with `gcc` while external c++ program (no guards there) compiled with `g++` -- working

`make check` fails because of swig timestamp, but `swig -python -threads -o pyccl/ccl_wrap.c pyccl/ccl.i` doesn`t produce any files

### CODE REVIEW

**Comment by philbull** [comment]
Can we add a make rule that compiles a trivial C++ program, please? This would allow any user to easily test compatibility with C++ on their system.

**Comment by elisachisari** [comment]
@vrastil do you think you could add a make rule as @philbull has suggested? Then we can review and merge

**Comment by vrastil** [comment]
@philbull @elisachisari I added make rule `check-cpp` and it works for me on Ubuntu with `g++`. Can you test this on different systems as well?

**Comment by elisachisari** [comment]
@vrastil I tried it on Mac. It seems to work but it gives me a warning.
Will travis know of this new make check automatically or do we need to do something to add it? @fjaviersanchez 
screen shot 2017-11-06 at 10 07 32 am

**Comment by vrastil** [comment]
@elisachisari I do not get this warning but I think it is only by suffix of ***tests/ccl_sample_run.c*** Can you try changing the suffix to ***.cpp*** and check again? If that works I can add simple cpp wrapper ***tests/ccl_sample_run.cpp*** containing the same code as C version to get rid of this warning

**Comment by vrastil** [comment]
@elisachisari I removed the ***.cpp*** version and modified `make check-cpp` to create its simply copy by `#include "ccl_sample_run.c"`

**Comment by elisachisari** [comment]
Great, thanks. Could you add the relevant documentation in the note and the README within this branch?

**Comment by vrastil** [comment]
I added info about C++ into README and doc to installation procedures, not sure whether it should be moved to some other parts

compiling in travis succeed but there is a problem with dynamic library, I should probably export some `LD_LIBRARY_PATH` before this step, or we can omit running the ***ccl_sample_run***?

**Comment by elisachisari** [comment]
@vrastil Does the check involve running `ccl_sample_run` or just compiling it? Does the problem arise in both cases?

**Comment by vrastil** [comment]
Without runnig the program the Travis build succeeds

**Comment by vrastil** [comment]
tested on Ubuntu with g++ v6 and on Debian g++ v4

**Comment by elisachisari** [comment]
@vrastil Looks like we merged with master at the same time. I don't think that generates any problems, it's just redundant.
But I did run into one problem with the compiler on my Mac desktop when makeing check-cpp:
screen shot 2017-11-08 at 16 58 25

**Comment by vrastil** [comment]
@elisachisari It seems that clang doesn`t support debug option `-Og`, I will look for alternatives and try to use autotools-generated variables for debug mode

**Comment by elisachisari** [comment]
Ok, thanks. It looks like travis is now failing after the merge. It seems there is a conflict with ccl_sample_run due to the implementation of baryons. I'm looking into it.

**Comment by vrastil** [comment]
@elisachisari OK, problem in ***ccl_sample_run*** seems fine. I couldn't find anything in autotools to pregenerate debug flags but now they should be OK for most compilers (hopefully all). Please test it on machine where it was failing.

**Comment by elisachisari** [comment]
@vrastil There's a different issue this time. Now the compiler can't file gsl
screen shot 2017-11-08 at 17 46 13
Any ideas what modifications caused this?

**Comment by vrastil** [comment]
I think that this error was there previously, it just fail earlier due to `-Og`. And CCL compiled fined? No errors due to `gsl`?

**Comment by elisachisari** [comment]
CCL was ok, make check runs without problems.

**Comment by vrastil** [comment]
When you performed the `./configure` step, did you use some extra `CFLAGS` or `LDFLAGS`?

**Comment by elisachisari** [comment]
I add a prefix:
./configure --prefix=/home/chisarie

**Comment by vrastil** [comment]
@elisachisari I don't know why it is failing, if you didn't specify gsl location then it should be in some default look-up location...I tried add some other flags where to look into `make check-cpp`, you can try it. I'm a little afraid that it won't work

**Comment by elisachisari** [comment]
@vrastil Success! ccl_sample_run compiles and runs now in my system with cpp :) Go ahead and merge!

**Comment by vrastil** [comment]
@elisachisari Glad to hear that! :)

**Pull request merged**
