### PR TITLE
WIP v1 release

### PR DESCRIPTION
**Pull request by beckermr**
This PR has documentation and associated changes for the v1 release.

To do:
- [x] rebase this PR on master and make sure tests pass (@beckermr will do this)
- [x] Actually changing "vx" to "v1" where necessary (README, etc etc)
- [x] Refresh doxygen docs
- [x] fix docker
- [x] update the changelog
- [x] Make sure CCL note is up to date and documenting v1
- [x] Fresh install and check all tests pass (even slow ones).
  - [x] @beckermr 
    - [x] python
    - [x] C
  - [x] @damonge 
    - [x] python
    - [x] C

To do after this PR is merged:
- [ ] tag the repo at v1
- [ ] Refresh the readthedocs
- [ ] make a github release
- [ ] upload to pypi
- [ ] set the default branch to the releases/1.0
- [x] remove stale branches
- [x] Other...? Please add to this list.

### CODE REVIEW

**Comment by elisachisari** [comment]
I'm starting a list of tasks to get CCL to v1:

- [ ] Actually changing "vx" to "v1" where necessary (README, etc etc)
- [ ] Refresh the readthedocs
- [ ] Refresh the pip install page
- [ ] Refresh doxygen docs
- [ ] Make sure CCL note is up to date and documenting v1
- [ ] Other...? Please add to this list.

**Comment by beckermr** [comment]
I moved the list to the top comment so we can find it easier.

**Comment by elisachisari** [comment]
Looked into the readthedocs page: https://readthedocs.org/projects/ccl/, the v1 can only be refreshed once the tag is there, so this is probably the last ting we'll do and after merging this PR.

**Comment by beckermr** [comment]
@elisachisari Sorry about the force push and rebase. The doxygen refresh you did was generating tons of merge conflicts because I did not yet have a chance to rebase this PR. The rebase is now done and I redid the refresh of the doxygen docs.

**Comment by beckermr** [comment]
@elisachisari Make sure to pull a fresh copy of the branch before push commits back up.

**Comment by beckermr** [comment]
I totally forget what I meant by "Refresh the pip install page". 🤦‍♂️ If anyone has any ideas LMK...

**Comment by beckermr** [comment]
UGH.

```bash
TEST 66/93 corrs:analytic_fftlog WARNING: ERROR: Cannot make log-spaced array with 0 points - need at least 2

ERROR 1026: ccl_correlation.c: ccl_tracer_corr_fftlog ran out of memory
```

**Comment by beckermr** [comment]
OK @sjoudaki It appears that your changes to the C test suite mean it now fails and/or uses huge amounts of memory. It nearly bricked my machine just now. Please debug this and push a fix. Then we can restart the v1 release process.

**Comment by beckermr** [comment]
OK. All of my tests pass. Thanks @sjoudaki for helping me debug things!

**Comment by elisachisari** [comment]
@beckermr I think that was me saying something about "refreshing the pip install" - I meant create a new release :) Instructions are in the CONTRIBUTING.md so should be straightforward.

**Comment by beckermr** [comment]
I think we will need someone with permissions to push to pypi. I do not have them. Does anyone know what the situation is here?

**Comment by damonge** [comment]
@EiffL (or maybe @elisachisari or @fjaviersanchez can do it).

**Comment by elisachisari** [comment]
Yes, I think I have permission to do it

**Comment by elisachisari** [comment]
Turns out pypi should trigger an update automatically as soon as we make a new release, so we can cross that out. We should verify, of course, that this has happened after we tag.

**Comment by EiffL** [comment]
The automated pypi actually never worked correctly,  I think there is a problem with some of the symbols in the password we used for pypi, but manual upload works, happy to take care of it.

**Comment by elisachisari** [comment]
Given that we have completed the list of tasks above, I'm approving and merging this PR.

**Pull request merged**
