### PR TITLE
Add methods to dump and read parameters to/from YAML

### PR DESCRIPTION
**Pull request by joezuntz**
It would be great to have a nice robust serialization code for the Parameters object.

This is not that code - the parameters have a fixed order and changing it will break things.   But it does work to dump and load a ccl_parameter object to and from a fixed YAML format, which is human readable, and will work as a placeholder until something more useful is done.

### CODE REVIEW

**Comment by joezuntz** [comment]
Apparently something I did only works on python 3 (or possibly with a different version of swig) - I'll check it out.

**Comment by elisachisari** [comment]
Also, could you check the decrease in coverage and the conflict with `ccl_core.h`?

**Comment by joezuntz** [comment]
I've added a new ipython notebook demonstrating this (Parameters.read_yaml is a class method; it doesn't need an actual instance of Parameters to be run - you use it like `Parameters.read_yaml(filename)`).

I've merged master in and fixed the issue.

I think there was only one line from this PR that wasn't tested, which was one of the error pathways.  I've added a test for that now, so let's see if that ups the coverage.  I think the other decreases may have been because I hadn't merged in master yet.

**Comment by elisachisari** [comment]
Looks like coverage is still down. Could you take another look?

**Comment by joezuntz** [comment]
I don't understand what versions coverall is comparing.  The changes marked in red here, for example:
https://coveralls.io/builds/19335596/source?filename=pyccl/core.py
aren't ones that are made in this PR.

**Comment by joezuntz** [comment]
Can we just ignore the coverage thing and merge, assuming you're happy with the other things you mentioned?  It clearly isn't working here.

**Comment by elisachisari** [comment]
Yes, I was waiting for the other tests to pass. Happy to merge this.

**Pull request merged**
