### PR TITLE
BUG use proper pk everywhere for RSD transfer function

### LINKED ISSUE #635: BUG RSD + number counts ignores input power spectrum
It appears the RSD + number counts transfer function is ignoring the input power spectrum. See `ccl_cls.c` around line 722

### PR DESCRIPTION
**Pull request by beckermr**
This PR makes sure to use the proper power spectrum for all of the RSD window functions. 

closes #635

### CODE REVIEW

**Comment by beckermr** [comment]
Note this bug is only on master since it involves the new 2d power spectrum interpolation structures.

**Comment by damonge** [comment]
Looks good. Just to clarify that the "bug" was there on purpose for a reason: you can pass any P(k) you want as the python Pk2D object, and it doesn't have to be the matter power spectrum (e.g. you can use this to pass a galaxy HOD power spectrum, which is what we're doing in the LSS HSC analysis). In that case, you want the power spectrum that enters the RSD term to still be the matter power spectrum.

However, the whole thing is inconsistent right now anyway, because with the current formulation you end up multiplying everything by the Pk2D in the end. Since this will all be irrelevant once the generalized tracers are in place (working on it), I'm happy for this to be merged right away.

**Comment by beckermr** [comment]
Ack. Missed the physics here. Should we close this issue?

**Comment by beckermr** [comment]
OK. I am going to close this since it is my stupidity.

**Comment by damonge** [comment]
wait, did you not merge this? I think it would have been fine to do so!

**Comment by beckermr** [comment]
Yeah I decided against it. If you are going to change the code anyways, there is no reason.

**Comment by damonge** [comment]
OK, as long as this doesn't prevent someone's analysis right now, I'm happy

**Comment by beckermr** [comment]
I noticed this while studying the code for adding openmp.

**Pull request closed without merging**
